Respect genotype filtering / FT tag when calculating AC/AN/AF
samtools/htsjdk pull request #1554
Opened 2021-06-01 17:32 UTC by RoriCremer

### Description

A gate has been added to the getCalledChrCount() method to not count filtered out genotypes.
This fixes a bug in which AC/AN/AF were calculated without respecting if the genotypes were filtered out (and therefore shouldn't be used for calculations)
Re Laura: "It’s probably pretty rare that a user had FT fields they ignored, but if so they should unfilter rather then have some janky arg to ignore FT in annotation."

A filtering unit test has been updated since getCalledChrCount() changes based on filtering

Still in draft form while I work out the following:

### Things to think about before submitting:
- [ ] Make sure your changes compile and new tests pass locally.
- [ ] Add new tests or update existing ones:
  - A bug fix should include a test that previously would have failed and passes now.
  - New features should come with new tests that exercise and validate the new functionality.
- [ ] Extended the README / documentation, if necessary
- [ ] Check your code style.
- [ ] Write a clear commit title and message
  - The commit message should describe what changed and is targeted at htsjdk developers
  - Breaking changes should be mentioned in the commit message.

2021-06-04 13:51 UTC, ldgauthier approved these changes
Thanks for the fix!  My only suggestion would be to add a comment to note explicitly that the first two genotypes in the test are PASS since this behavior is a little bit different for VCs versus Genotypes.

2021-06-04 19:57 UTC, lbergelson requested changes
@RoriCremer Looks good, 1 comment about clarifying the test name.  Once that's addressed 👍 to merge.

2021-06-04 19:57 UTC, lbergelson commented on src/test/java/htsjdk/variant/variantcontext/VariantContextUnitTest.java
> +    public void testGenotypeFilters() {
Could we rename this to testGenotypeCountsRespectGenotypeFilters or something along those lines?

2021-06-10 15:33 UTC, lbergelson approved these changes
👍

2021-06-10 15:37 UTC, merged