Remove remaining incorrect zero-length-B-array checks and exception throwing
samtools/htsjdk pull request #1669
Opened 2023-06-13 10:03 UTC by jmarshall

PR #1194 removed a number of `Array.getLength(value) == 0` checks when setting B-array tagged fields, as such empty tagged field values had recently been made explicitly valid in SAM/BAM/CRAM files.

Unfortunately the existing such check in `setUnsignedArrayAttribute()` was omitted from that PR and has now caused the issue raised in samtools/hts-specs#728. Whatever additional problems might (but probably don't) exist elsewhere in the HTSJDK code for ML tags, this check for a generic zero-length array was incorrect and should be removed. A test case for `setUnsignedArrayAttribute()` has also been added.

In grepping for other candidates, I noticed one other potentially incorrect looking `Array.getLength` invocation.

This was in `Slice::setAttribute()`, which appears to set an optional tag in a Slice header. There are currently no such tags defined, so the question is somewhat moot but — as a separate commit for your consideration — I have also removed that check. (As there are no such tags currently defined, there are no test cases for these fields to which a test exercising this change could be added.)

2023-06-14 19:13 UTC, gileshall reviewed
Tagging @droazen for additional review. Changes look fine to me.

Since we have a use case in the wild, is there any merit in testing it with a contrived VCF replicating the pathology or is this too cumbersome / overkill?

2023-06-22 15:59 UTC, droazen requested changes
@jmarshall Thanks for this patch! It looks fine to me, but to make sure that the cram codepath can handle empty arrays I think it would be advisable to add a cram unit test as well.

2023-06-22 19:53 UTC, jmarshall commented
I am not a Java programmer and I am not familiar with your test suite or how to set up a CRAM unit test in it.

I provided this pull request to get the ball rolling, as there had been no response to my comment on #1194 notifying the HTSJDK maintainers of this problem. If the maintainers think this applying this change requires additional unit tests, they should add such tests themselves or use this PR as inspiration for their own fix for this problem.

2023-06-22 20:16 UTC, jmarshall commented on src/main/java/htsjdk/samtools/cram/structure/Slice.java
> -        }
As I mentioned, there are no current unit tests for this Slice attribute functionality and the slice tag functionality is currently unused in the format. If you think this _Slice.java_ change is dubious, please discard the second commit.

2023-06-23 19:16 UTC, droazen commented
No problem @jmarshall, @gileshall has kindly volunteered to complete this PR. Thanks for getting the ball rolling

2023-07-24 20:45 UTC, cmnbroad commented
@gileshall Sorry - I'm a bit late in looking at this. Since this method is unused by the CRAM code, I'd propose that we just remove it rather than adding a test to cover it.

2023-07-24 20:50 UTC, cmnbroad commented
Also, FWIW, the `Slice` class has pretty extensive unit test coverage, distributed across a few test files, with the primary ones being in the [SliceTests](https://github.com/samtools/htsjdk/blob/master/src/test/java/htsjdk/samtools/cram/structure/SliceTests.java) class.

2023-08-03 21:57 UTC, lbergelson commented
This was finished in #1674.  Thank you everyone who contributed.

2023-08-03 21:57 UTC, closed without merging

2023-08-03 22:57 UTC, jmarshall commented
Thanks, I'm glad this made it into the release. 🎉 

I wouldn't mind if you wanted to put “by @gileshall and @jmarshall” in the release notes. (And this PR's title “Remove remaining incorrect zero-length-B-array checks” is perhaps a better summary one-liner.)

2023-08-04 03:55 UTC, lbergelson commented
@jmarshall Ah, sorry about that.  I made sure it credited you in the actual commit but I just hit the button for "generate some lazy release notes" and it apparently doesn't include co-authors.  I've updated it.  My recent commit message work has been pretty bad.  Zero-length array is better than the accidental string of 6 commits that all say "fix" that I merged before that because I hadn't noticed it was set to rebase and not squash...

2023-08-04 04:02 UTC, jmarshall commented
NBD but thanks — it's good to have things to point to if people ask me what I spend my time on…

Bad luck about your string of “fixes” :smile: